#!/usr/bin/env python3
"""Render a mapa_operacional projection (permanent, non-weekly Mapa-OS reading) as
print-ready A4 HTML, using the EXECUTAR design tokens and the same component
vocabulary as assets/templates/executive-report-a4.html (card, metric, callout,
pill, section-head, table). Unlike the Prisma A4 template (fixed 3-face, 100
named placeholders), this content is variable-length (N macroáreas, N domínios
each), so it is generated by looping over the payload rather than substituting
into a fixed set of placeholders.

Uso:
  python3 render_mapa_operacional.py payload.json output.html
"""
from __future__ import annotations

import json
import sys
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS_CSS = (ROOT / "assets" / "tokens" / "tokens.css").read_text(encoding="utf-8")

REQUIRED_TOP_LEVEL = [
    "meta", "visao_geral", "como_ler_a_planilha", "mapa_operacional",
    "estrutura_da_planilha", "pontos_de_atencao", "legenda_executiva",
    "fonte_e_rastreabilidade",
]


def validate(data: dict) -> None:
    missing = [k for k in REQUIRED_TOP_LEVEL if k not in data]
    if missing:
        raise ValueError(f"Payload inválido: faltam chaves de topo: {missing}")
    if not data["mapa_operacional"].get("macroareas"):
        raise ValueError("Payload inválido: mapa_operacional.macroareas vazio")


def e(v) -> str:
    return escape(str(v)) if v is not None else ""


STYLE = f"""
{TOKENS_CSS}

* {{ box-sizing:border-box; }}
html {{ background:#ddd; }}
body {{
  margin:0;
  background:var(--exec-color-surface-shell);
  color:var(--exec-color-ink-title);
  font-family:"IBM Plex Sans","Helvetica Neue",Arial,sans-serif;
  font-size:10.5pt;
  line-height:1.42;
  -webkit-print-color-adjust:exact;
  print-color-adjust:exact;
}}

.report-title-string {{ string-set:report-title content(text); }}
.report-meta-string {{ string-set:report-meta content(text); }}

@page {{ size:A4 portrait; margin:15mm 16mm 18mm; }}
@page cover {{ size:A4 portrait; margin:0; }}
@page report {{
  size:A4 portrait;
  margin:15mm 16mm 18mm 16mm;
  @top-left {{ content:string(report-title); font-family:Arial,sans-serif; font-size:8pt; color:var(--exec-color-ink-secondary); }}
  @top-right {{ content:"EXECUTAR"; font-family:Arial,sans-serif; font-size:8pt; font-weight:700; color:var(--exec-color-ink-title); }}
  @bottom-left {{ content:string(report-meta); font-family:Arial,sans-serif; font-size:7.5pt; color:var(--exec-color-ink-muted); }}
  @bottom-right {{ content:counter(page) " / " counter(pages); font-family:Arial,sans-serif; font-size:7.5pt; color:var(--exec-color-ink-muted); }}
}}

.cover {{
  page:cover; width:210mm; height:297mm; padding:22mm 20mm 18mm;
  display:grid; grid-template-rows:auto 1fr auto;
  background:linear-gradient(180deg, rgba(0,191,99,.03), transparent 33%), var(--exec-color-surface-shell);
  position:relative; overflow:hidden; break-after:page;
}}
.cover::after {{
  content:""; position:absolute; right:-34mm; bottom:-38mm; width:125mm; height:125mm;
  border:1px solid var(--exec-color-accent-soft-strong); border-radius:50%;
  box-shadow:0 0 0 18mm rgba(0,191,99,.025), 0 0 0 38mm rgba(31,147,255,.018);
}}
.brand {{ display:flex; align-items:center; gap:10px; font-weight:700; letter-spacing:-.02em; font-size:15pt; }}
.brand-mark {{
  width:10mm; height:10mm; border-radius:3mm; display:grid; place-items:center;
  background:var(--exec-color-brand); color:var(--exec-color-ink-inverse); font-weight:700; font-size:13pt;
}}
.eyebrow {{
  display:inline-flex; align-items:center; gap:7px; color:var(--exec-color-brand-strong);
  font-size:8pt; font-weight:700; letter-spacing:.08em; text-transform:uppercase;
}}
.eyebrow::before {{ content:""; width:9mm; height:1.2pt; background:var(--exec-color-brand); }}
.cover-main {{ align-self:center; max-width:165mm; position:relative; z-index:1; }}
.cover h1 {{ margin:7mm 0 5mm; font-size:29pt; line-height:1.08; letter-spacing:-.04em; }}
.cover .dek {{ font-size:13pt; line-height:1.45; color:var(--exec-color-ink-secondary); max-width:150mm; }}
.cover .obj {{ font-size:10.5pt; line-height:1.5; color:var(--exec-color-ink-secondary); max-width:150mm; margin-top:5mm; }}
.cover-meta {{
  position:relative; z-index:1; display:grid; grid-template-columns:1fr auto; gap:8mm; align-items:end;
  padding-top:8mm; border-top:.35pt solid var(--exec-color-rule-default); color:var(--exec-color-ink-secondary); font-size:9pt;
}}
.kicker {{ font-size:7.5pt; letter-spacing:.08em; text-transform:uppercase; font-weight:700; color:var(--exec-color-ink-muted); margin-bottom:2mm; }}

.report-page {{ page:report; break-after:page; position:relative; }}
.report-page:last-child {{ break-after:auto; }}
.avoid-break, .card, table, .callout, .metric {{ break-inside:avoid; }}
h1,h2,h3 {{ break-after:avoid; margin-top:0; }}
p {{ orphans:3; widows:3; margin-top:0; }}

.section-head {{
  display:grid; grid-template-columns:auto 1fr; gap:5mm; align-items:end;
  margin-bottom:6mm; padding-bottom:3.5mm; border-bottom:.35pt solid var(--exec-color-rule-default);
}}
.section-no {{ font-family:"IBM Plex Mono",monospace; font-size:9pt; color:var(--exec-color-brand-strong); font-weight:700; }}
.section-head h2 {{ margin:0; font-size:17pt; letter-spacing:-.02em; }}
.lead {{ font-size:11pt; line-height:1.5; color:var(--exec-color-ink-secondary); max-width:165mm; margin-bottom:6mm; }}

.grid-2 {{ display:grid; grid-template-columns:1fr 1fr; gap:5mm; }}
.grid-4 {{ display:grid; grid-template-columns:repeat(4,1fr); gap:3.5mm; }}
.stack {{ display:grid; gap:4mm; }}

.card {{ border:.35pt solid var(--exec-color-rule-default); border-radius:12px; padding:5mm; background:var(--exec-color-surface-page); }}
.card.soft {{ background:var(--exec-color-surface-sunken); border-color:transparent; }}

.metric {{ padding:4mm 4mm 3.5mm; border-top:1.8pt solid var(--exec-color-brand); background:var(--exec-color-surface-sunken); }}
.metric .value {{ font-size:19pt; font-weight:600; line-height:1; letter-spacing:-.03em; }}
.metric .label {{ margin-top:2mm; font-size:8pt; color:var(--exec-color-ink-secondary); }}
.metric .obs {{ margin-top:1mm; font-size:7.2pt; color:var(--exec-color-ink-muted); }}

.callout {{ border-left:3pt solid var(--exec-color-data-fill-alt); padding:4mm 5mm; background:var(--exec-color-accent-soft); border-radius:0 8px 8px 0; }}
.callout strong {{ display:block; margin-bottom:1.2mm; }}

.pill {{
  display:inline-flex; padding:1.2mm 2.6mm; border-radius:999px; font-size:7.2pt; font-weight:700;
  color:var(--exec-color-brand-strong); background:var(--exec-color-brand-soft); white-space:nowrap;
}}
.pill.muted {{ color:var(--exec-color-ink-secondary); background:var(--exec-color-surface-sunken-alt); }}
.pill.warn {{ color:#7A3A0B; background:#FBEFE3; }}

table {{ width:100%; border-collapse:collapse; font-size:8.4pt; line-height:1.35; }}
th {{
  text-align:left; font-size:7.2pt; letter-spacing:.04em; text-transform:uppercase; color:var(--exec-color-ink-secondary);
  background:var(--exec-color-surface-sunken); border-top:.7pt solid var(--exec-color-rule-strong);
  border-bottom:.7pt solid var(--exec-color-rule-strong); padding:2.4mm 2.2mm;
}}
td {{ vertical-align:top; border-bottom:.35pt solid var(--exec-color-rule-default); padding:2.6mm 2.2mm; }}

.macro-card {{ border:.35pt solid var(--exec-color-rule-default); border-radius:12px; padding:4.5mm 5mm; margin-bottom:4mm; break-inside:avoid; }}
.macro-head {{ display:flex; justify-content:space-between; align-items:baseline; gap:4mm; margin-bottom:1.5mm; }}
.macro-head h3 {{ font-size:12pt; margin:0; letter-spacing:-.01em; }}
.macro-num {{ font-family:"IBM Plex Mono",monospace; font-size:8pt; color:var(--exec-color-ink-muted); }}
.macro-finalidade {{ font-size:8.8pt; color:var(--exec-color-ink-secondary); margin-bottom:2.5mm; }}
.macro-dominios {{ display:grid; gap:1.8mm; margin-bottom:2.5mm; }}
.dominio-row {{ font-size:8.2pt; }}
.dominio-nome {{ font-weight:600; }}
.dominio-docs {{ color:var(--exec-color-ink-secondary); }}
.macro-foot {{ display:flex; justify-content:space-between; align-items:center; font-size:7.6pt; color:var(--exec-color-ink-muted); border-top:.35pt solid var(--exec-color-rule-subtle); padding-top:2mm; }}

.term-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:3mm 8mm; }}
.term {{ font-size:8.6pt; }}
.term dt {{ font-weight:700; color:var(--exec-color-ink-title); }}
.term dd {{ margin:0.6mm 0 0; color:var(--exec-color-ink-secondary); }}

.trace-note {{ margin-top:4mm; padding-top:2.5mm; border-top:.35pt solid var(--exec-color-rule-default); color:var(--exec-color-ink-muted); font-size:7.2pt; line-height:1.4; }}

@media screen {{
  body {{ max-width:210mm; margin:16px auto; box-shadow:0 0 25px rgba(0,0,0,.12); }}
  .report-page {{ padding:15mm 16mm 18mm; }}
}}
@media print {{
  html,body {{ background:#fff; }}
  body {{ max-width:none; box-shadow:none; }}
  .report-page {{ padding:0; }}
}}
"""


def render_cover(meta: dict, visao: dict) -> str:
    return f"""
<section class="cover">
  <div class="brand"><span class="brand-mark">E</span><span>EXECUTAR</span></div>
  <div class="cover-main">
    <div class="eyebrow">{e(meta.get('tipo_de_mapa', 'Mapa operacional'))}</div>
    <h1>{e(meta.get('titulo'))}</h1>
    <p class="dek">{e(meta.get('subtitulo'))}</p>
    <p class="obj">{e(meta.get('objetivo'))}</p>
  </div>
  <div class="cover-meta">
    <div>
      <div class="kicker">Fonte primária</div>
      <strong>{e(meta.get('fonte_principal'))}</strong>
    </div>
    <div style="text-align:right">
      <div class="kicker">Referência</div>
      <span>{e(meta.get('data_de_referencia'))}</span>
    </div>
  </div>
</section>
"""


def render_visao_geral(visao: dict) -> str:
    cards = ""
    for n in visao.get("numeros_chave", []):
        obs = f'<div class="obs">{e(n.get("observacao",""))}</div>' if n.get("observacao") else ""
        cards += f"""
    <div class="metric">
      <div class="value">{e(n['valor'])}</div>
      <div class="label">{e(n['rotulo'])}</div>
      {obs}
    </div>"""
    return f"""
<section class="report-page">
  <div class="section-head"><div class="section-no">01</div><h2>Visão geral</h2></div>
  <p class="lead">{e(visao.get('resumo'))}</p>
  <div class="grid-4" style="margin-bottom:6mm">{cards}
  </div>
</section>
"""


def render_como_ler(passos: list) -> str:
    items = ""
    for p in passos:
        items += f"""
    <div class="card soft">
      <span class="pill">Passo {e(p['passo'])}</span>
      <h3 style="margin-top:2.5mm; font-size:10.5pt">{e(p['titulo'])}</h3>
      <p style="font-size:8.6pt; color:var(--exec-color-ink-secondary)">{e(p['descricao'])}</p>
    </div>"""
    return f"""
<section class="report-page">
  <div class="section-head"><div class="section-no">02</div><h2>Como ler a planilha</h2></div>
  <div class="stack">{items}
  </div>
</section>
"""


def render_macroarea(m: dict) -> str:
    dominios = m.get("dominios", [])
    if not dominios:
        dom_html = '<p style="font-size:8.2pt; color:var(--exec-color-ink-muted)">Sem domínio mapeado.</p>'
    else:
        rows = ""
        for d in dominios:
            docs = ", ".join(doc["nome"] for doc in d.get("documentos_principais", [])) or "—"
            rows += f"""
      <div class="dominio-row"><span class="dominio-nome">{e(d['nome'])}</span> <span class="macro-num">({e(d.get('rastreio_id',''))})</span><br>
      <span class="dominio-docs">{e(docs)}</span></div>"""
        dom_html = f'<div class="macro-dominios">{rows}</div>'
    return f"""
  <div class="macro-card">
    <div class="macro-head">
      <h3>{e(m['nome'])}</h3>
      <span class="macro-num">{e(m['rastreio_id'])}</span>
    </div>
    <div class="macro-finalidade">{e(m['finalidade_executiva'])}</div>
    {dom_html}
    <div class="macro-foot">
      <span>{e(m['quantidade_de_campos'])} campos · {e(m['aba_de_preenchimento'])}</span>
      <span>{e(m['situacao'])}</span>
    </div>
  </div>"""


def render_mapa_operacional(mo: dict) -> str:
    macros = mo.get("macroareas", [])
    # 5 per page to keep each page reasonably dense but not overflowing
    pages = []
    chunk = 5
    for i in range(0, len(macros), chunk):
        group = macros[i:i + chunk]
        cards = "".join(render_macroarea(m) for m in group)
        head = f"""<div class="section-head"><div class="section-no">03</div><h2>{e(mo['titulo'])}</h2></div>""" if i == 0 else ""
        lead = f"""<p class="lead">{e(mo['descricao'])}</p>""" if i == 0 else ""
        pages.append(f"""
<section class="report-page">
  {head}
  {lead}
  {cards}
</section>""")
    return "".join(pages)


def render_estrutura(est: dict) -> str:
    def tbl(rows, headers):
        head = "".join(f"<th>{e(h)}</th>" for h in headers)
        body = ""
        for r in rows:
            body += "<tr>" + "".join(f"<td>{e(v)}</td>" for v in r) + "</tr>"
        return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"

    visoes = tbl([(v["aba"], v["funcao"]) for v in est.get("visoes_de_leitura", [])], ["Aba", "Função"])
    registros = tbl([(r["aba"], r["funcao"]) for r in est.get("registros_estruturais", [])], ["Aba", "Função"])
    entrada = est.get("entrada_humana", {})
    return f"""
<section class="report-page">
  <div class="section-head"><div class="section-no">04</div><h2>Estrutura da planilha</h2></div>
  <div class="callout" style="margin-bottom:5mm">
    <strong>Entrada humana</strong>
    {e(entrada.get('abas'))} — {e(entrada.get('funcao'))} {e(entrada.get('regra'))}
  </div>
  <div class="grid-2">
    <div>
      <h3 style="font-size:10.5pt">Abas de visão</h3>
      {visoes}
    </div>
    <div>
      <h3 style="font-size:10.5pt">Registros estruturais</h3>
      {registros}
    </div>
  </div>
</section>
"""


def render_pontos_atencao(pontos: list) -> str:
    items = ""
    for p in pontos:
        rastreio = ", ".join(p.get("rastreio", []))
        items += f"""
    <div class="callout">
      <strong>{e(p['titulo'])}</strong>
      {e(p['descricao'])}
      <div style="margin-top:1.5mm"><span class="pill muted">{e(rastreio)}</span></div>
    </div>"""
    return f"""
<section class="report-page">
  <div class="section-head"><div class="section-no">05</div><h2>Pontos de atenção</h2></div>
  <div class="stack">{items}
  </div>
</section>
"""


def render_legenda_e_fonte(legenda: list, fonte: dict) -> str:
    terms = ""
    for t in legenda:
        terms += f"""<div class="term"><dt>{e(t['termo'])}</dt><dd>{e(t['significado'])}</dd></div>"""
    abas = ", ".join(fonte.get("abas_principais_de_rastreio", []))
    return f"""
<section class="report-page">
  <div class="section-head"><div class="section-no">06</div><h2>Legenda executiva</h2></div>
  <dl class="term-grid">{terms}
  </dl>
  <div class="trace-note">
    Fonte: {e(fonte.get('planilha'))} · abas de rastreio: {e(abas)} · {e(fonte.get('regra'))}
  </div>
</section>
"""


def build_html(data: dict) -> str:
    meta = data["meta"]
    body = render_cover(meta, data["visao_geral"])
    body += f"""<span class="report-title-string" style="display:none">{e(meta.get('titulo'))}</span>"""
    body += f"""<span class="report-meta-string" style="display:none">{e(meta.get('fonte_principal'))} · {e(meta.get('data_de_referencia'))}</span>"""
    body += render_visao_geral(data["visao_geral"])
    body += render_como_ler(data["como_ler_a_planilha"])
    body += render_mapa_operacional(data["mapa_operacional"])
    body += render_estrutura(data["estrutura_da_planilha"])
    body += render_pontos_atencao(data["pontos_de_atencao"])
    body += render_legenda_e_fonte(data["legenda_executiva"], data["fonte_e_rastreabilidade"])

    return f"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(meta.get('titulo'))} — EXECUTAR</title>
<style>{STYLE}</style>
</head>
<body>
{body}
</body>
</html>
"""


def main() -> int:
    if len(sys.argv) != 3:
        print("uso: render_mapa_operacional.py payload.json output.html", file=sys.stderr)
        return 2
    payload_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
    data = json.loads(payload_path.read_text(encoding="utf-8"))
    try:
        validate(data)
    except ValueError as err:
        print(f"ERRO: {err}", file=sys.stderr)
        return 2
    html = build_html(data)
    out_path.write_text(html, encoding="utf-8")
    print(f"PASS: {out_path}; macroareas={len(data['mapa_operacional']['macroareas'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
